name: Build and Test from PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  build-and-test-from-comment:
    if: |
      github.event.issue.pull_request
      && startsWith(github.event.comment.body, '/run-tests')
      && (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: maven-settings-action
        uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # commit hash references to v4.0.0
        with:
          servers: '[{"id": "mulesoft-ee-releases", "username": "${env.MULE_REPO_USER}", "password": "${env.MULE_REPO_PASSWORD}"}]'
          repositories: '[{"id": "mulesoft-ee-releases", "name": "MuleSoft EE Releases", "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"}]'

      - name: Build and test
        env:
          MULE_REPO_USER: ${{ secrets.MULE_REPO_USER }}
          MULE_REPO_PASSWORD: ${{ secrets.MULE_REPO_PASSWORD }}
        run: mvn -B clean verify
